- docs/DeveloperGuide.md
Update
1. Targer user profile
2. Value proposition
3. User Stories
> Update DG developer guide

- docs/AboutUs.md
Just added the name, 
Will add picture later.
> Update AboutUs page with information about Rajarshi

- docs/DeveloperGuide.md
Edit Uses Cases
1. Add a customer
2. Delete a customer
3. List customers
> Update DG Developer Guide- Use Cases

- docs/UserGuide.md
Add the details of the new Add command to the User Guide
> Update User Guide with updated Add command

- src/main/java/seedu/address/logic/commands/ListCommand.java
Pre-exisitng List command already sufficient
Minor changes to string return message, 
"list of customers" instead of original "list of person" etc
> Update List Command

- src/main/java/seedu/address/model/customer/Car.java
- src/main/java/seedu/address/model/customer/CoeExpiry.java
New attribute classes, to be integrated as needed. 
Should be independent of whatever address field fixes need to be made.
> Add new attributes to be intergrated

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
- src/main/java/seedu/address/storage/JsonAdaptedCustomer.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
- src/test/java/seedu/address/testutil/CustomerBuilder.java
> Command execution error fix

- build.gradle
- docs/DeveloperGuide.md
Add DG 5 lines for v1.3 requirement and enable gradle assertions
> Add DG 5 lines for v1.3 requirement and enable gradle assertions

- docs/UserGuide.md
> no message

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/customer/Customer.java
- src/main/java/seedu/address/model/customer/DateOfBirth.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedCustomer.java
- src/main/java/seedu/address/ui/CustomerCard.java
- src/main/resources/view/CustomerListCard.fxml
- src/test/data/JsonAddressBookStorageTest/invalidAndValidCustomerAddressBook.json
- src/test/data/JsonAddressBookStorageTest/invalidCustomerAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicateCustomerAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidCustomerAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalCustomersAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/storage/JsonAdaptedCustomerTest.java
- src/test/java/seedu/address/testutil/CustomerBuilder.java
- src/test/java/seedu/address/testutil/CustomerUtil.java
- src/test/java/seedu/address/testutil/EditCustomerDescriptorBuilder.java
- src/test/java/seedu/address/testutil/TypicalCustomers.java
Add the date of birth attribute. The following sections have been accounted for:
* Add command
* Edit command
* User interface + FXML
* Storage
> Branch date of birth attribute

- docs/UserGuide.md
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/customer/Car.java
- src/main/java/seedu/address/storage/JsonAdaptedCar.java
- src/main/java/seedu/address/storage/JsonAdaptedCustomer.java
Car class now has 2 string attributes carBrand, carType
This would help with future functionality
As we encapsulate carBrand, carType into Car class
Existing
Customer
-phone,name,email,
-carsOwned<Car, coe exp date>
Proposed 1.
Customer
-phone,name,email,
-carsOwned<Car, coe exp date>
-CarPreference<Car>
> Add string attributes(carBrand, carType) to model.customer.Car class

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/customer/Car.java
- src/main/java/seedu/address/model/customer/Customer.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedCustomer.java
- src/main/java/seedu/address/ui/CustomerCard.java
- src/main/resources/view/CustomerListCard.fxml
- src/test/java/seedu/address/storage/JsonAdaptedCustomerTest.java
- src/test/java/seedu/address/testutil/CustomerBuilder.java
> Add carPreference attribute

- src/main/java/seedu/address/logic/filters/CoeExpiryFilter.java
- src/main/java/seedu/address/model/customer/Car.java
- src/main/java/seedu/address/model/customer/CoeExpiry.java
- src/test/java/seedu/address/logic/filters/CoeExpiryFilterTest.java
- src/test/java/seedu/address/testutil/CustomerBuilder.java
Adds COE Expiry filter and test code based on convention from Customer attributes and other commands, where appropriate
> Add COE expiry filter

- src/main/java/seedu/address/logic/filters/CoeExpiryFilter.java
- src/main/java/seedu/address/logic/filters/NameFilter.java
- src/test/java/seedu/address/logic/filters/CoeExpiryFilterTest.java
- src/test/java/seedu/address/logic/filters/NameFilterTest.java
Add name filter. Not completely tested yet so further testing will be pushed back later.
Bug fixes might be needed but just quickly put this in to meet deadline.
> Add name filter

- src/main/java/seedu/address/logic/filters/CarFilter.java
- src/main/java/seedu/address/logic/filters/CarsOwnedFilter.java
- src/main/java/seedu/address/logic/filters/CarsPreferredFilter.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/customer/Car.java
Shared parent CarFilter class to enclose common methods for matching carBrand, carType attributes
> Add CarsOwnedFilter and CarsPreferredFilter

- src/main/java/seedu/address/ui/CommandBox.java
Basically, if your command starts with /up then it will just put the text you last had on the commandbox again. kindof like doing a up arrow in the terminal
> Add last command retrieval using /up

- docs/UserGuide.md
Some changes made:
* DOB details
* COE filter details
* Corrections to the EMAIL feature
> Add improvements to UG

- docs/UserGuide.md
> Re-add Tip

- docs/UserGuide.md
Also note that we cannot properly escape pipe characters within tables in Intellij.
> Fix User Guide documentation for c/ and cp/ tags

- docs/UserGuide.md
- src/main/java/seedu/address/model/customer/CoeExpiry.java
- src/main/java/seedu/address/model/customer/DateOfBirth.java
As current implementation lack b/ birthdate attribute
> Update UG add command examples and Resolve invalid Date inputs

- src/main/java/seedu/address/model/customer/DateOfBirth.java
date of birth to be no more than 100 years before current date
> Date of birth range restriction 

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
Find command singularity return message
List command status message for empty customer list
> list command and find command status message 

- docs/UserGuide.md
> Remove misplaced Tip box

- docs/DeveloperGuide.md
- docs/UserGuide.md
Appendix for effort and manual testing
As per DG requirements
> Appendix for effort and manual testing
